# Generated by Django 5.2 on 2025-04-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_currency_userprofile_monthly_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dólar Estadounidense ($)'), ('GBP', 'Libra Esterlina (£)'), ('MXN', 'Peso Mexicano ($)'), ('BRL', 'Real Brasileño (R$)')], default='BRL', max_length=3),
        ),
    ]
