# Generated by Django 5.2 on 2025-05-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dólar Estadounidense ($)'), ('GBP', 'Libra Esterlina (£)'), ('MXN', 'Peso Mexicano ($)'), ('BRL', 'Real Brasileño (R$)'), ('CUP', 'Peso Cubano (₱)')], default='BRL', max_length=3),
        ),
    ]
